global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: 'thinkmoreforum-backend'
    scrape_interval: 5s
    metrics_path: "/actuator/prometheus"
    tls_config:
      cert_file: /etc/prometheus/prometheus/api.thinkmoreapp.com_bundle.crt
      key_file: /etc/prometheus/prometheus/api.thinkmoreapp.com.key
      insecure_skip_verify: true
    static_configs:
      - targets: ['localhost:443']